version: '2.4'

services:
  terraform:
    build:
      context: .
      args:
        TAG: 0.12.6
    image: docker-registry/terraform:0.12.6
    tty: true
    stdin_open: true
    environment:
      TF_VAR_vsphere_server: ${vsphere_server}
      TF_VAR_vsphere_user: ${vsphere_user}
      TF_VAR_vsphere_password: ${vsphere_password}
    volumes:
    - ./:/opt/terraform/
    - /var/run/docker.sock:/var/run/docker.sock
