version: '2.4'

services:
  go:
    image: golang:stretch
    tty: true
    stdin_open: true
    working_dir: /go/src/github.com/ContainX/docker-volume-netshare   # using original path for "package-reasons"
    environment:
      GOPATH: /go
    volumes:
    - .:/go/src/github.com/ContainX/docker-volume-netshare
    entrypoint: ["/bin/bash"]
